name: Java CI and Git Action

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0

    - name: Run chmod to make gradlew executable
      run: chmod +x ./gradlew

    - name: Build with Gradle Wrapper
      run: ./gradlew build

    - name: copy file via ssh password to server
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.HOST }}
        username: hee
        key: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        source: build/libs/demo-0.0.1-SNAPSHOT.jar
        target: /home/hee/v2
        strip_components: 2

    - name: start start.sh
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.HOST }}
        username: hee
        key: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        command_timeout: 3m
        script:
          sh start.sh
